const express = require('express')
const morgan = require('morgan')
const helmet = require('helmet')
const cors = require('cors')
const MOIVES = require('./MOVIES.json')

const app = express()
app.use(morgan('dev'))
app.use(helmet())
app.use(cors())